#ifndef __KRANEWM__KEYBIND__GUARD__
#define __KRANEWM__KEYBIND__GUARD__

#include "x_wrapper/key.hh"

#include <map>

// TODO group
enum KeyOperation
{
    KEY_NOOP = 0,
    QUIT, ZOOM, TOGGLE_FLOAT, TOGGLE_FULLSCREEN,
    TOGGLE_SHADE, CENTER_CLIENT,
    TOGGLE_ICONIFY, POP_ICONIFIED,
    DEICONIFY_1, DEICONIFY_2, DEICONIFY_3,
    DEICONIFY_4, DEICONIFY_5, DEICONIFY_6,
    DEICONIFY_7, DEICONIFY_8, DEICONIFY_9,
    SPAWN_TERMINAL, SPAWN_QUICKTERM, SPAWN_QUICKTERMTMUX,
    SPAWN_DMENUPASS, SPAWN_DMENUPASSCOPY, SPAWN_DMENU,
    SPAWN_BROWSER, SPAWN_SEC_BROWSER,
    SPAWN_NEOMUTT, SPAWN_RANGER, SPAWN_SNCLI, SPAWN_RTV,
    SPAWN_7LOCK, SPAWN_SAGE, SPAWN_GPICK, SPAWN_QALCULATE,
    SPAWN_IRSSI, SPAWN_NEWSBOAT, RHYTHMBOXSHOW,
    RHYTHMBOXTOGGLE, RHYTHMBOXNEXT, RHYTHMBOXPREV, RHYTHMBOXSTOP,
    MPCTOGGLE, MPCNEXT, MPCPREV, MPCSTOP, MPCRANDOM, MPCSINGLE,
    VOLUMEUP, VOLUMEDOWN, VOLUMEMUTE,
    BRIGHTNESSUP15, BRIGHTNESSDOWN15,
    BRIGHTNESSUP5, BRIGHTNESSDOWN5,
    TAKE_SCREENSHOT, TAKE_SCREENSHOT_SEL,
    KILL_CLIENT, MOVE_CLIENT_FWD, MOVE_CLIENT_BCK,
    FLOAT_GROW_UP, FLOAT_GROW_DOWN,
    FLOAT_GROW_LEFT, FLOAT_GROW_RIGHT,
    FLOAT_SHRINK_UP, FLOAT_SHRINK_DOWN,
    FLOAT_SHRINK_LEFT, FLOAT_SHRINK_RIGHT,
    FLOAT_UP_OR_STACK_FWD, FLOAT_DOWN_OR_STACK_BCK,
    FLOAT_LEFT_OR_MASTER_FWD, FLOAT_RIGHT_OR_MASTER_BCK,
    MARK_CLIENT, JUMP_TO_MARKED,
    STICK, MAXIMIZE,
    INC_NMASTER, INC_GAPSIZE, INC_MRATIO, DEC_NMASTER,
    DEC_GAPSIZE, DEC_MRATIO, INC_MFACTOR, DEC_MFACTOR,
    FLOAT, TILE, DECK, DOUBLEDECK, GRID, MONOCLE,
    SWAP_ORIENTATION, TOGGLE_LAYOUT,
    JUMP_MASTER, JUMP_STACK, JUMP_LAST, JUMP_PANE,
    JUMP_CLIENT_1, JUMP_CLIENT_2, JUMP_CLIENT_3,
    JUMP_CLIENT_4, JUMP_CLIENT_5, JUMP_CLIENT_6,
    JUMP_CLIENT_7, JUMP_CLIENT_8, JUMP_CLIENT_9,
    FOCUS_FWD, FOCUS_BCK,
    DOWN_STACK, UP_STACK,
    DOWN_MASTER, UP_MASTER,
    ACTIVATE_WORKSPACE_1, ACTIVATE_WORKSPACE_2,
    ACTIVATE_WORKSPACE_3, ACTIVATE_WORKSPACE_4,
    ACTIVATE_WORKSPACE_5, ACTIVATE_WORKSPACE_6,
    ACTIVATE_WORKSPACE_7, ACTIVATE_WORKSPACE_8,
    ACTIVATE_WORKSPACE_9, TOGGLE_WORKSPACE,
    ACTIVATE_NEXT_WS, ACTIVATE_PREV_WS,
    TOGGLE_SCRATCHPAD_1, TOGGLE_SCRATCHPAD_2,
    CLIENT_TO_NEXT_WORKSPACE, CLIENT_TO_PREV_WORKSPACE,
    CLIENT_TO_WORKSPACE_1, CLIENT_TO_WORKSPACE_2,
    CLIENT_TO_WORKSPACE_3, CLIENT_TO_WORKSPACE_4,
    CLIENT_TO_WORKSPACE_5, CLIENT_TO_WORKSPACE_6,
    CLIENT_TO_WORKSPACE_7, CLIENT_TO_WORKSPACE_8,
    CLIENT_TO_WORKSPACE_9, CLIENT_TO_SCRATCHPAD_1,
    CLIENT_TO_SCRATCHPAD_2
};

struct KeyShortcut
{
    KeyShortcut(KeySym _keysym, unsigned _mask)
      : keysym(_keysym), mask(_mask) {}

    KeySym keysym;
    unsigned mask;
};

inline bool
operator<(const KeyShortcut& ks1, const KeyShortcut& ks2)
{
    auto cmp1 = ks1.keysym + 10000 * ks1.mask;
    auto cmp2 = ks2.keysym + 10000 * ks2.mask;
    return cmp1 < cmp2;
}

typedef ::std::map<KeyShortcut, KeyOperation> KeyBinds;

#endif//__KRANEWM__KEYBIND__GUARD__
